<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ZonesSeeder extends Seeder
{
    public function run()
    {
        $zones = [
            'SAMAN TARAZONERO II',
            'SAMAN TARAZONERO I',
            'LA MACARENA',
            'VILLAS DEL CARMEN',
            'LA ESPERANZA',
            'TURMERITO',
            'LA MACAREÑA',
            'VILLA LOS TAMARINDOS',
            'DR LACENIO GUERRERO',
            'VALLE DEL ROSARIO',
            'LUIS BERTI',
            'VILLAS SAN JOSE',
            'TAGUAPIRE',
            'PARAISO',
            'JABILLAR I',
            'JABILLAR II',
            'JABILLAR III',
            'SIMON BOLIVA4R',
            'SAN SEBASTIAN',
            'EL MANANTIAL',
            'SANTA BARBARA',
            'SANTA EDUVIGES',
            'ANTONIO JOSE DE SUCRE',
            'SAMAN DE GUERE',
            'JUAN PABLO II',
            'LAS CAYENAS',
            'SAMANCITO',
            'BARRIO APOLO',
            'VALLE DORADO',
            'LEOCOLVO',
            'GUANARITO',
            'GUANARITO LA CANDELARIA',
            'BRISA DE LOS ANGELES',
            'GUANARITO VIRGEN DE LA COROMOTO',
            'GUANARITO 6 DE ENERO',
            'VILLA CASTIN',
            'CACIQUE GUAICAIPURO',
            'VILLEGUITA I',
            'PATRIA NUEVA',
            'LOS INOCENTES, VILLEGAS',
            'LAS PALMAS',
            'SANTIAGO MARIñO',
            'VILLEGAS',
            'PLAZA JARDIN',
            'NUEVA VILLEGAS',
            'LOS CAOBOS I',
            'LOS CAOBOS II',
            '19 DE ABRIL',
            'LA TRINIDAD',
            'EL NARANJAL',
            'ANCA',
            'RAFAEL HERNANDES',
            'GONZALITO',
            'GUERITO',
            'LA MAGDALENA',
            'LA CONCEPCION',
            'LA CONCEPCION EDIF',
            'SOROCAIMA I',
            'SOROCAIMA II',
            'SOROCAIMA III',
            'RAFAEL CALDERA',
            'ARTURO MICHELENA',
            'ESTEBAN LIENDO',
            'VILLA MAKRO',
            'SECTOR 1',
            'CASONA I CALLE',
            'RESC LOS JARDINES (EDIFICIOS)',
            'LA CASONA II CALLE',
            'LA CASONA II EDIFICIO',
            'VILLAS DE SUR',
            'LA CANDELARIA',
            'MAURO SALAZAR',
            'LA ENCRUCIJADA',
            'HOTEL PLAZA',
            'HOTEL LOS JARDINES',
            'HOTEL AVEIRON',
            'LA HERREREÑA',
            'VILLA GEICA',
            'PAYITA',
            'LA MARCELOTA',
            'LA GUSMAN',
            'LA GUSMAN VALLE DEL RIO',
            'MATA CABALLO',
            'PANTIN',
            'RIO SECO',
            'FUNDA BARRIO',
            'LA ARBOLEDA',
            'VALLECITO',
            'VALLE VERDE',
            '1RO DE MAYO',
            'LAS RURALES',
            'EL CAMBUR-PAYA',
        ];

        foreach ($zones as $zone) {
            DB::table('zones')->insert([
                'name' => trim($zone),
            ]);
        }
    }
}

